# Generated by Django 3.0.8 on 2020-08-05 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200804_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', related_query_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
